apiVersion: v1
description: A Helm chart for deployment of TI-KeyRelease
name: ti-key-release-1
home: https://github.com/IBM/trusted-service-identity
maintainers:
  - name: Brandon Lum
    email: Brandon.Lum@ibm.com
  - name: Mariusz Sabath
    email: sabath@us.ibm.com
