# Default values for ti-key-relase-1
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# target namespace for the deployment
namespace: trusted-identity

# target docker repo
tiRepo: trustedseriviceidentity

# Cluster Information
cluster:
  name: cluster-name
  region: dal01

# Section related to JWT token creation
jwt:
  # expireSec - Time To Live for JWT token (in seconds)
  expireSec: 60
  issuer: wsched@us.ibm.com

secrets:
  # how often secrets should be retrieved from Vault
  refreshSec: 600

# specify the address of the Vault service that contains all
# the TSI secrets to be retrieved by the sidecar
vaultAddress: http://vault

# Not recommended for user to configure this. Hyperkube image to use when executing
# kubectl commands
hyperkube:
  repository: gcr.io/google_containers/hyperkube
  tag: v1.14.3
