apiVersion: v1
appVersion: "1.0"
description: A Helm chart for setting up TSI nodes
name: tsi-node-setup
version: 1.5.0
home: https://github.com/IBM/trusted-service-identity
maintainers:
  - name: Brandon Lum
    email: Brandon.Lum@ibm.com
  - name: Mariusz Sabath
    email: sabath@us.ibm.com
