apiVersion: v1
kind: ConfigMap
metadata:
  name: tsi-mutate-set-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "ti-key-release.name" . }}
    chart: {{ template "ti-key-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  tsi-mutate-configmap.yaml: |-
    {{- include "tsi-mutate-configmap.yaml.tpl" . | indent 4}}
  tsi-mutate-update.sh: |-
    {{- include "tsi-mutate-update.sh.tpl" . | indent 4}}
  certmaker.sh: |-
    {{- include "certmaker.sh.tpl" . | indent 4}}
  mutatingwebhook.yaml: |-
    {{- include "mutatingwebhook.tpl" . | indent 4}}
