
apiVersion: batch/v1
kind: Job
metadata:
  name: tsi-mutate-configmap-update
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: {{ template "ti-key-release.name" . }}
    chart: {{ template "ti-key-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: tsi-mutate-configmap-update
      labels:
        app: {{ template "ti-key-release.name" . }}
        chart: {{ template "ti-key-release.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: ti-install-sa
      containers:
        - name: hyperkube
          image: "{{ .Values.hyperkube.repository }}:{{ .Values.hyperkube.tag }}"
          command: ["sh", "-c", "/tmp/ti-key-release/tsi-mutate-update.sh"]
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: "/tmp/ti-key-release"
              name: tmp-ti-key-release-configmap
      volumes:
        - name: tmp-ti-key-release-configmap
          configMap:
            name: tsi-mutate-set-configmap
            # this makes the files executable
            defaultMode: 0744
      restartPolicy: OnFailure
