{{ define "tsi-mutate-configmap.yaml.tpl" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tsi-mutate-webhook-configmap
data:
  tsiMutateConfig.yaml: |
      sidecarContainers:
      - name: jwt-sidecar
        image: {{ .Values.tiRepo }}/ti-jwt-sidecar:{{ .Values.tiVersion }}
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JWT_TTL_SEC
          value: {{ .Values.jwt.expireSec }}
        - name: VAULT_ADDR
          value: {{ .Values.vaultAddress }}
        - name: SECRET_REFRESH_SEC
          value: {{ .Values.secrets.refreshSec }}
        volumeMounts:
          - name: tsi-secrets
            mountPath: /usr/share/secrets
          - name: tsi-sockets
            mountPath: "/host/sockets"
          - name: pod-metadata
            mountPath: /pod-metadata
            readOnly: true
          - name: host-etc
            mountPath: /host/etc
            readOnly: true
      volumes:
        - name: tsi-secrets
          emptyDir: {}
        - name: tsi-sockets
          hostPath:
            # directory location on host
             path: /tsi-secure/sockets
             # directory must exist
             type: Directory
        - name: host-etc
          hostPath:
            # directory location on host
             path: /etc
             type: Directory
        - name: pod-metadata
          downwardAPI:
            items:
              - path: "tsi-secrets"
                fieldRef:
                 fieldPath: metadata.annotations['tsi.secrets']
              - path: "ti-identity"
                fieldRef:
                  fieldPath: metadata.annotations['admission.trusted.identity/ti-identity']
              - path: "ti-pod-name"
                fieldRef:
                  fieldPath: metadata.name
              - path: "ti-pod-namespace"
                fieldRef:
                  fieldPath: metadata.namespace
              - path: "ti-images"
                fieldRef:
                  fieldPath: metadata.annotations['admission.trusted.identity/ti-images']
              - path: "ti-cluster-name"
                fieldRef:
                  fieldPath: metadata.annotations['admission.trusted.identity/ti-cluster-name']
              - path: "ti-cluster-region"
                fieldRef:
                  fieldPath: metadata.annotations['admission.trusted.identity/ti-cluster-region']
      addVolumeMounts:
        - name: tsi-secrets
          mountPath: /tsi-secrets
          readOnly: true
{{ end }}
