apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: ti-injector-webhook-deployment
  labels:
    app: ti-injector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ti-injector
    spec:
      serviceAccountName: ti-sa
      containers:
        - name: ti-injector
          image: lumjjb/ti-injector:v1
          imagePullPolicy: Always
          args:
            - -initcontainerCfgFile=/etc/webhook/config/initcontainerconfig.yaml
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
      volumes:
        - name: webhook-certs
          secret:
            secretName: ti-injector-webhook-certs
        - name: webhook-config
          configMap:
            name: ti-injector-webhook-configmap
