apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ index .Values "ti-key-release-1" "namespace" }}
  name: tsi-mutate-webhook-deployment
  labels:
    app: tsi-mutate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsi-mutate
  template:
    metadata:
      labels:
        app: tsi-mutate
    spec:
      serviceAccountName: ti-sa
      containers:
        - name: tsi-mutate
          image: {{ .Values.tiRepo }}/ti-webhook:{{ .Values.tiVersion }}
          imagePullPolicy: Always
          # webhook must be running as root to listen to events on port 443
          securityContext:
            runAsUser: 0
          args:
            - -tsiMutateConfigFile=/etc/webhook/config/tsiMutateConfig.yaml
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
            - name: tsi-namespace
              mountPath: /etc/webhook
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: tsi-mutate-webhook-certs
        - name: webhook-config
          configMap:
            name: tsi-mutate-webhook-configmap
        - name: tsi-namespace
          downwardAPI:
            items:
              - path: "tsi-namespace"
                fieldRef:
                  fieldPath: metadata.namespace
