apiVersion: v1
description: A Helm chart for deployment of TI-KeyRelease
name: ti-setup
version: 1.2.0
home: https://github.ibm.com/kompass/TI-KeyRelease
maintainers:
  - name: Brandon Lum
    email: Brandon.Lum@ibm.com
  - name: Mariusz Sabath
    email: sabath@us.ibm.com
